### ISSUE TITLE
Add Eliot as Logging system

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#149]
Investigate the option to use [Eliot](https://eliot.readthedocs.io/en/stable/index.html) as Logging system

the benefits are:

1. more clean log review and visualization
2. better asyncio support
3. better unit testing integration
4. the logs can be mixed with the profiler results to generate a more detailed code profiling view

┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/15xpa5z) by [Unito](https://www.unito.io)

**Comment by garciparedes** [comment]
Closing this issue as it is moved to https://github.com/minos-framework/minos-python/issues/29
