### ISSUE TITLE
Parameterize encoder/decoder on `MinosStorageLmdb`

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#198]
Currently, the `minos.common.MinosStorageLmdb` class uses the `minos.common.MinosAvroValuesDatabase`. This issue is intended to extend that behaviour to support any `MinosBinaryProtocol` class such that custom encode/decode implementations are used.

**Comment by andrea-mucci** [comment]
the code issue was merged, can i close?

**Comment by garciparedes** [comment]
Yes! I'll close it. Thanks @andrea-mucci 🙂
