### ISSUE TITLE
Provide a description for `minos.common.model` module classes.

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#225]
In order to improve the ease of understanding of the `minos.common.model` module, mainly composed by the `MinosModel, `ModelField`, `Event`, `Command` and `CommandReply` classes, it's needed to increase the degree of explicability of the classes and important method.

For classes, a good starting point could be composed:
* A relatively small but descriptive description about the class.
* Maybe a small description about the cases for which the class was created.

For methods: 
* A relative small description about the purpose of the method.
* A small example inside the `docstring`

**Comment by albamig** [comment]
Content of this issue will be accomplished in #259
