### ISSUE TITLE
Provide a description for `minos.common.repository` module classes.

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#226]
In order to improve the ease of understanding of the `minos.common.repository` module, mainly composed by the `MinosRepository`, `MinosRepositoryEntry`, `MinosInMemoryRepository` and `PostgreSqlMinosRepository` classes, it's needed to increase the degree of explicability of the classes and important method.

For classes, a good starting point could be composed:
* A relatively small but descriptive description about the class.
* Maybe a small description about the cases for which the class was created.

For methods: 
* A relative small description about the purpose of the method.
* A small example inside the `docstring` 

This issue is closely related to https://github.com/Clariteia/minos_microservice_common/issues/225

**Comment by albamig** [comment]
Content of this issue will be accomplished in #259
