### ISSUE TITLE
Add a `CONTRIBUTING.md` file.

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#232]
The `CONTRIBUTING.md` file must provide a descriptive guide about how to set up the development environment, how to create Pull Requests with changes, etc.

For the Development Environment setup:
*  `Python` version and an easy way to install (`pyenv`)
*  `Poetry` and how to install.
*  Services to be running in background (`PostgresQL`, `Kafka`, etc.) and how to start it easily (a `docker-compose` template).
* Describe the main command in the `Makefile` and how to run tests.
* Explain how to configure the `pre-commit` and what it does.

Related to Pull Requests:
* Explain that before starting to code must exists an Issue explaining the changes.
* Create a branch that follow the `issue-${ISSUE_NUM}-${ISSUE_SUMMARY}` pattern.
* The Pull Request must be created as soon as possible and mark as draft until it's ready for reviewing.
* ...

**Comment by albamig** [comment]
Content of this issue will be accomplished in #259
