### ISSUE TITLE
Refactor aggregate's update and delete

### ISSUE THREAD

**Issue by albamig** [Clariteia/minos_microservice_common#269]
The update and delete methods in Aggregate class are called through a decorator self_or_classmethod which makes them able to get called either from an instante of Aggregate or the class itself. For instance both ​`a = Aggregate.create(); a.update()` and `Aggregate.update()` behave the same way.

In my opinion, this adds complexity for a use case that should not be provided (the second one).

Since the object oriented way of dealing with updates is to always modify a previously created object, I propose to refactor this to a more straightforward implementation as an instance method.

What do you think of this @garciparedes?

**Comment by garciparedes** [comment]
Hi @albamig!

I agree with you that having multiple ways to do the same thing is not a good practice, as it could dramatically increase the code complexity in the future. In any case, I decided to provide the two alternatives (instance and class calling to `update` and `delete`) for these two reasons:
* Allowing to directly call these methods from the instance will keep the business logic clean and readable as it's the most natural way to perform changes over an instance.
* Allowing to call those methods without needing to create instances will increase the system performance as it won't need to recreate (call the `Snapshot` to obtain the latest and full version of the `Aggregate`) for update and delete operations, which I think could provide a big performance improvement.

Despite that, we can discuss more about this topic as it's a foundational part of the `minos` framework and needs to be clarified as much as possible.

What do you think about this @Clariteia/core-devs? 🙂
