### ISSUE TITLE
Remove inheritance from `object`

### ISSUE THREAD

**Issue by albamig** [Clariteia/minos_microservice_common#272]
Since Python3, inheritance from `object` is implicit.

I propose to refactor all classes inheriting `object` to the new style. For instance:
`class MinosRepositoryEntry(object):` should be `class MinosRepositoryEntry:`.

**Comment by garciparedes** [comment]
I thought that this was a good coding practice, but I realised that I was wrong. If we integrate the `pyupgrade` package, we could fix that kind of things automatically as this case is among the ones that this tool covers: https://github.com/asottile/pyupgrade#new-style-classes
