### ISSUE TITLE
Model must support custom validation methods

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#28]
The Model class must support a custom validation attribute method.

the name of the method must respect a specific format:

```python

class UserModel(MinosModel):
    name: str

    def validate_name(self, name: str) -> bool:
         return (name is "Hello")

```

the format must be:

```python

validate_{attribute name}

```

and must return True or False

In case of Fasle the ModelClass must raise and Attribute Exception

**Comment by garciparedes** [comment]
This issue is currently blocked by #34
