### ISSUE TITLE
Recover `avro_schema` from byte-encoded avro instance

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#302]
Currently, the class implementation with the responsibility to encode and decode avro instances is `minos.common.MinosAvroProtocol`. This class implements the `encode(value: dict, schema: dict) -> bytes` and `decode(raw: bytes) -> dict` methods which serialises and deserialises instances to the avro format.

The purpose of this issue is to extend this class functionality in such way that we can recover the original schema. Maybe, one solution would be to add an additional method like `decode_schema(raw: bytes) -> dict` or something similar, that retrieves the avro schema from the serialised instance.

This issue is part of the https://github.com/Clariteia/minos_microservice_common/issues/301, which aims to fully recover a `MinosModel` instance dinamically.

**Comment by vladyslav-fenchak** [comment]
Proposal:
I will create the following method inside minos.common..protocol.avro.base.MinosAvroProtocol, this way you can get only the avro_schema if needed:

```python
class MinosAvroProtocol(MinosBinaryProtocol):
    """Minos Avro Protocol class."""
    ....
    @classmethod
    def decode_schema(cls, data: bytes, *args, **kwargs) -> Union[tuple[list, Any]]:
        """Decode the given bytes of data into a single dictionary or a sequence of dictionaries.

        :param data: A bytes object.
        :param args: Additional positional arguments.
        :param kwargs: Additional named arguments.
        :return: A tuple or a list of tuples.
        """

        try:
            with io.BytesIO(data) as file:
                r = reader(file)

                try:
                    schema = r.writer_schema
                except Exception as ex:
                    raise MinosProtocolException(f"Error getting avro schema: {ex}")

        except Exception as exc:
            raise MinosProtocolException(f"Error decoding the avro bytes: {exc}")

        return schema
```

**Comment by garciparedes** [comment]
Hi @vladyslav-fenchak, it looks really good! Only a small detail:

Why not to test test that the `decoded_schema` is equal to a expected one?

In your case:
```
{
    "type": "record",
    "name": "tests.model_classes.ShoppingList",
    "fields": [
        {
            "name": "user",
            "type": [
                {
                    "type": "record",
                    "name": "tests.model_classes.User",
                    "fields": [
                        {"name": "id", "type": "int"},
                        {"name": "username", "type": ["string", "null"]},
                    ],
                },
                "null",
            ],
        },
        {"name": "cost", "type": "float"},
    ],
}
```

This will help us to avoid strange bugs related with the behaviour of this new function 😉
