### ISSUE TITLE
Refactor `minos.common.model.abc.fields`

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_common#316]
Make public and Move 

- [ ] _MinosModelFromAvroBuilder
- [ ] _MinosModelAvroSchemaBuilder
- [ ] _ModelFieldCaster 

to separate files to avoid excessive file length and complexity.

**Comment by vladyslav-fenchak** [comment]
@garciparedes adds if there is anything else to refactor.

**Comment by garciparedes** [comment]
HI @vladyslav-fenchak, I also created an issue for that same purpose (https://github.com/Clariteia/minos_microservice_common/issues/317). I'll proceed to close the another one but I'll include the description as a quote to this one.

**Comment by garciparedes** [comment]
Here is the description of #316:

> Currently, the `minos/common/model/abc/fields.py` file contains the following classes:
> 
> * `ModelField`: main module's class
> * `_ModelFieldCaster`: parses the values to check if they are valid.
> * `_MinosModelFromAvroBuilder`: builds the type hinting based on a given `avro` schema
> * `_MinosModelAvroSchemaBuilder`: builds the `avro` schema based on a given type hinting.
> * `_MinosModelAvroDataBuilder`: builds the `avro` data based on a given value.
> 
> As this file contains more than 500 lines of code, I propose to split it into single class files inside a `minos/common/model/abc/fields/` directory.
