### ISSUE TITLE
`TypedDict` instances do not implement equality as expected.

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_common#335]
Currently, the `typing.TypedDict` class is used as the class that models the type of any aggregate, containing the `classname` and the `type_hints` (a dictionary in which the keys are the field names and the values are the field types).

This class (which is provided by the Python's standard library) fits really well for mostly all of the tasks we need to use it, except one of them: The equality comparison of types.

As we want to use types to define the structure of the instances to be send across micro-services, we need to compute equality by value and not by reference. That is, we want to use types that behaves in the following way:
```python
TypedDict("Foo", {"text": str}) == TypedDict("Foo", {"text": str})  # True
```

Unfortunately, the `typing.TypedDict` does not works as expected. Then, to solve that trouble I propose to define a `minos`-defined class that provides the same functionality, but also performs the equal as expected.

**Comment by andrea-mucci** [comment]
I prefer to extend the class with equality verification

**Comment by garciparedes** [comment]
The main trouble about using inheritance is that the `TypedDict` is a helper function that internally creates a `type`, which has a special and fixed parameterisation so I think that a possible solution will be to imitate that implementation as we need to inherit from `type` to be compatible with all the Python's typing system.

**Comment by garciparedes** [comment]
Finally, the approach I decided to follow is to extend the `type` "class" and use class methods for building purposes as the `type`-inherited classes constructor cannot be redefined with a different pattern. 

You can see a preview of the brand new `minos.common.ModelType` here 🤗: https://github.com/Clariteia/minos_microservice_common/blob/5c93b8df91392105e9fec433da4ad72fe5da50fc/minos/common/model/types.py#L96-L159
