### ISSUE TITLE
Add more test for configuration Environment and Parametrized Mappers

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_common#440]
There are some configurations that do not have  full test coverage: 

- [ ] minos.common.configuration.config._ENVIRONMENT_MAPPER
- [ ] minos.common.configuration.config._PARAMETERIZED_MAPPER

┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/17nw21f) by [Unito](https://www.unito.io)

**Comment by garciparedes** [comment]
Closing this issue as it is moved to https://github.com/minos-framework/minos-python/issues/36
