### ISSUE TITLE
The Model must have a method ( static ) that help to convert multiple ModelBase instances

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#49]
The model base must have a staticmethod that receive as a parameter a list of ModelBase inherited instances and return a binary with a list of that instances

```python

list_instances = ModelBase.convert([model_instance_one, model_instance_two])

```

**Comment by garciparedes** [comment]
This issue is been resolved on #39 with the `MinosModel.to_avro_bytes(...)` class method.
