### ISSUE TITLE
Event Model

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#5]
The Event Model must inherit from the Model Base Class

the Event Model must have the following parameter:

* topic: str
* model: str
* items: AggregateModel

pseudo code:

```python
     order_instance = OrderAggregate()
     .....
     class EventModel(ModelBase):
             topic: str
             model: str
             items: AggregateModel

     class OrderCreatedEvent(EventModel):
             topic: str = "OrderCreated"
             model: str = "OrderAggregate"
           

     new_event = OrderCreatedEvent(items=order_instance)
```

The EventModel must be used by the EventManager Service and by the EventBroker Service

**Comment by garciparedes** [comment]
This issue is already resolved by https://github.com/Clariteia/minos_microservice_common/issues/55
