### ISSUE TITLE
ModelBase must have a static method for load binary data

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#50]
ModelBase must have a static method that load a binary data and convert in a single or a list of ModelBase inherited instances.

```python

instances_loaded = ModelBase.load(binary_data)

```

in case of malformed binary data the method must raise a `MinosBinaryFormatException`

**Comment by garciparedes** [comment]
This issue is been resolved on #39 with the `MinosModel.from_avro_bytes(...)` class method.
