### ISSUE TITLE
Snapshot Service

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#58]
To get the most updated version of the Aggregate a PeriodicService must be created

the service in every interaction must:

1. get the latest Snapshot version ( specific snapshot table )
2.  get the updated list of actions from the Aggregate Table
3. get the diff and update the snapshot

the Periodic Service have a variable execution time, default time: 2 seconds

the Snapshot Table have:

id: int unique
aggregate_id: int unique
version: int
name: aggregate name str
binary: binary data aggregate

**DELETE**

the DELETE action must delete the snapshot

**Comment by garciparedes** [comment]
As the initial implementation of the `minos.common.Repository` will not be composed of the incremental changes (each row will store an snapshot of the aggregate) this issue is transformed to a _nice to have_  one, closely related to #84

**Comment by garciparedes** [comment]
Closing this issue because it was moved to https://github.com/Clariteia/minos_microservice_networks/issues/51
