### ISSUE TITLE
Command Model

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#6]
The Command Model must inherit from the Model Base Class

the Event Model must have the following parameter:

* command: str
* model: Optional[str]
* params: Optional[Any]
* reply_channel: Optional[str]

pseudo code:

```python
     order_aggregate_instance = OrderAggregate()
     ...
     class CommandModel(ModelBase):
             command: str
             model: Optional[str]
             params: Optional[Any]
             reply_channel: Optional[str]

     class AddTicketCommand(CommandModel):
             command: str = "AddTicket"
             model: Optional[str] = "Order"
             params: Optional[Any]
             reply_channel: Optional[str]

     new_command = AddTicketCommand(params=order_aggregate_instance, reply_channel="CreateOrderSaga")
```

The CommandModel class and his derived would be used by the SagaManager, the Command Manager and the CommandBroker

**Comment by garciparedes** [comment]
This issue is already resolved by https://github.com/Clariteia/minos_microservice_common/issues/56
