### ISSUE TITLE
Code autoreload in dev mode

### ISSUE THREAD

**Issue by albamig** [Clariteia/minos_microservice_common#668]
Currently, every single time we make changes in a microservice we need to restart it so the changes are applied.

I propose to study a way to perform code auto reload whenever a change has been performed to any file in the project, in order to speed up development.

**Comment by albamig** [comment]
I know `uvicorn` already provides this kind of functionality. For example you can deploy an app as:
```bash
uvicorn main:app --reload
```
and then `uvicorn` will reload every watched file whenever there are changes.

**Comment by garciparedes** [comment]
Closing this issue as it is moved to https://github.com/minos-framework/minos-python/issues/45
